// Code generated by "pipeline"; DO NOT EDIT.

package aether

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.AetherCryo, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.AetherCryo, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	// attack: ForeignFrostglint - 1-Hit DMG: {0}
	attack1 = []float64{
		0.44462,
		0.48081,
		0.517,
		0.5687,
		0.60489,
		0.64625,
		0.70312,
		0.75999,
		0.81686,
		0.8789,
		0.94094,
		1.00298,
		1.06502,
		1.12706,
		1.1891,
	}
	// attack: ForeignFrostglint - 2-Hit DMG: {1}
	attack2 = []float64{
		0.4343,
		0.46965,
		0.505,
		0.5555,
		0.59085,
		0.63125,
		0.6868,
		0.74235,
		0.7979,
		0.8585,
		0.9191,
		0.9797,
		1.0403,
		1.1009,
		1.1615,
	}
	// attack: ForeignFrostglint - 3-Hit DMG: {2}
	attack3 = []float64{
		0.52976,
		0.57288,
		0.616,
		0.6776,
		0.72072,
		0.77,
		0.83776,
		0.90552,
		0.97328,
		1.0472,
		1.12112,
		1.19504,
		1.26896,
		1.34288,
		1.4168,
	}
	// attack: ForeignFrostglint - 4-Hit DMG: {3}
	attack4 = []float64{
		0.58308,
		0.63054,
		0.678,
		0.7458,
		0.79326,
		0.8475,
		0.92208,
		0.99666,
		1.07124,
		1.1526,
		1.23396,
		1.31532,
		1.39668,
		1.47804,
		1.5594,
	}
	// attack: ForeignFrostglint - 5-Hit DMG: {4}
	attack5 = []float64{
		0.70778,
		0.76539,
		0.823,
		0.9053,
		0.96291,
		1.02875,
		1.11928,
		1.20981,
		1.30034,
		1.3991,
		1.49786,
		1.59662,
		1.69538,
		1.79414,
		1.8929,
	}
	// attack: ForeignFrostglint - Charged Attack DMG: {5}+{6}
	charge1 = []float64{
		0.559,
		0.6045,
		0.65,
		0.715,
		0.7605,
		0.8125,
		0.884,
		0.9555,
		1.027,
		1.105,
		1.183,
		1.261,
		1.339,
		1.417,
		1.495,
	}
	// attack: ForeignFrostglint - Charged Attack DMG: {5}+{6}
	charge2 = []float64{
		0.60716,
		0.65658,
		0.706,
		0.7766,
		0.82602,
		0.8825,
		0.96016,
		1.03782,
		1.11548,
		1.2002,
		1.28492,
		1.36964,
		1.45436,
		1.53908,
		1.6238,
	}
	// attack: ForeignFrostglint - Plunge DMG: {8}
	collision = []float64{
		0.639324,
		0.691362,
		0.7434,
		0.81774,
		0.869778,
		0.92925,
		1.011024,
		1.092798,
		1.174572,
		1.26378,
		1.352988,
		1.442196,
		1.531404,
		1.620612,
		1.70982,
	}
	// attack: ForeignFrostglint - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.278377,
		1.382431,
		1.486485,
		1.635134,
		1.739187,
		1.858106,
		2.02162,
		2.185133,
		2.348646,
		2.527025,
		2.705403,
		2.883781,
		3.062159,
		3.240537,
		3.418915,
	}
	// attack: ForeignFrostglint - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.596762,
		1.726731,
		1.8567,
		2.04237,
		2.172339,
		2.320875,
		2.525112,
		2.729349,
		2.933586,
		3.15639,
		3.379194,
		3.601998,
		3.824802,
		4.047606,
		4.27041,
	}
	// skill: IceFogPiercer - Skill DMG: {0}
	skillDMG = []float64{
		0.9168,
		0.98556,
		1.05432,
		1.146,
		1.21476,
		1.28352,
		1.3752,
		1.46688,
		1.55856,
		1.65024,
		1.74192,
		1.8336,
		1.9482,
		2.0628,
		2.1774,
	}
	// skill: IceFogPiercer - Ice Crystal DMG: {1}
	crystalDMG = []float64{
		0.21392,
		0.229964,
		0.246008,
		0.2674,
		0.283444,
		0.299488,
		0.32088,
		0.342272,
		0.363664,
		0.385056,
		0.406448,
		0.42784,
		0.45458,
		0.48132,
		0.50806,
	}
	// burst: FrostboundJavelin - Ice Javelin DMG: {0}/Strike
	burstJavelinDMG = []float64{
		0.55131,
		0.592658,
		0.634007,
		0.689137,
		0.730486,
		0.771834,
		0.826965,
		0.882096,
		0.937227,
		0.992358,
		1.047489,
		1.10262,
		1.171534,
		1.240447,
		1.309361,
	}
	// burst: FrostboundJavelin - Frostglow DMG Bonus: {1}
	burstFrostglowBonus = []float64{
		0.027565,
		0.029633,
		0.0317,
		0.034457,
		0.036524,
		0.038592,
		0.041348,
		0.044105,
		0.046861,
		0.049618,
		0.052374,
		0.055131,
		0.058577,
		0.062022,
		0.065468,
	}
	// burst: FrostboundJavelin - Stellar-Conduct Ice Javelin Single Strike DMG: {7}
	burstConductJavelinDMG = []float64{
		0.36754,
		0.395105,
		0.422671,
		0.459425,
		0.48699,
		0.514556,
		0.55131,
		0.588064,
		0.624818,
		0.661572,
		0.698326,
		0.73508,
		0.781022,
		0.826965,
		0.872907,
	}
	// burst: FrostboundJavelin - Stellar-Conduct Frostglow DMG Bonus: {8}
	burstConductFrostglowBonus = []float64{
		0.018377,
		0.019755,
		0.021134,
		0.022971,
		0.02435,
		0.025728,
		0.027565,
		0.029403,
		0.031241,
		0.033079,
		0.034916,
		0.036754,
		0.039051,
		0.041348,
		0.043645,
	}
	// burst: FrostboundJavelin - Stellar Swirl Ice Javelin Single Strike DMG: {9}
	burstSwirlJavelinDMG = []float64{
		0.55131,
		0.592658,
		0.634007,
		0.689137,
		0.730486,
		0.771834,
		0.826965,
		0.882096,
		0.937227,
		0.992358,
		1.047489,
		1.10262,
		1.171534,
		1.240447,
		1.309361,
	}
	// burst: FrostboundJavelin - Stellar Swirl Frostglow DMG Bonus: {10}
	burstSwirlFrostglowBonus = []float64{
		0.027565,
		0.029633,
		0.0317,
		0.034457,
		0.036524,
		0.038592,
		0.041348,
		0.044105,
		0.046861,
		0.049618,
		0.052374,
		0.055131,
		0.058577,
		0.062022,
		0.065468,
	}
)
