// Code generated by "pipeline"; DO NOT EDIT.

// passive: Traveler's Path # Weapon_Sword_WeaponQuestSnezhnaya
//
//	When the Traveler equips this, their ATK will increase by 16% for 8s after they hit
//	an opponent. At the same time, they will also regenerate 3 Elemental Energy. This
//	effect can trigger once every 5s. This can be triggered even when the character is
//	not on the field.
package exaiphanesblade

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.ExaiphanesBlade, NewWeapon)
}

const (
	passiveDuration = 8 // passive: TravelersPath
)

// passive: TravelersPath
var passiveATK = []float64{
	0.16,
	0.2,
	0.24,
	0.32,
	0.4,
}
